name: Integration

on:
  pull_request:
    types: [opened, edited]

jobs:

  label_pull_request:

    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix: 
        os: [ "ubuntu-latest", "windows-latest" ]
        python-version: [3.10]

    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PDM
      uses: pdm-project/setup-pdm@v2
      with:
        python-version: ${{ matrix.python-version }}
        enable-pep582: true

    - name: Install Dependencies
      run: pdm install

    - name: Test
      run: pytest tests/
    
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Black
        uses: psf/black@stable


